name: Linters Flow

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout written code
        uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Lint
        run: bash ./gradlew ktlintCheck

      - name: Submit lint report
        uses: actions/upload-artifact@v2
        with:
          name: Lint_report.html
          path: app/build/reports/lint-results-debug.html